# Introduction - Matrix algebra review

This page contains some basic reminder of matrix algebra using python numpy.

The following links has useful information whan converting from Matlab to numpy arrays:  
http://sebastianraschka.com/Articles/2014_matlab_vs_numpy.html  
https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#




Matrix with real elements:
$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$

The first index $n$ is the number of rows.  
The second index $m$ is the number of columns

Column vector of dimension $n$:
$\mathbf{a} = 
\begin{bmatrix}
a_{1}  \\
a_{2}  \\
\vdots \\
a_{n}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
$

Row vector of dimension $m$:

$\mathbf{b} = 
\begin{bmatrix}
b_1  & b_2 & \ldots b_{m} 
\end{bmatrix} \in \mathbb{R}^{1\times m}
$


In [193]:
import numpy as np
#from numpy import linalg as LA
np.set_printoptions(precision=3)

In [194]:
A = np.random.randint(9, size=(4, 5)) # creates random matrix with integer entries (from 0-9) and size (4,5)
A

array([[8, 8, 6, 1, 4],
       [3, 2, 7, 2, 4],
       [3, 5, 7, 0, 1],
       [1, 0, 7, 8, 2]])

In [195]:
a = np.array([[0],[2],[1],[6],[7]]) # numpy array representation of column vector as a 2d array of dimension (5,1)
a

array([[0],
       [2],
       [1],
       [6],
       [7]])

In [196]:
a.shape

(5, 1)

In [197]:
b = np.array([[1,2,3,6,7]]) # row vector
b

array([[1, 2, 3, 6, 7]])

In [198]:
b.shape

(1, 5)

In [199]:
np.zeros((5,1)) # column vector of zeros and dimension 5x1

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [200]:
np.ones((1,4)) # row vector of ones and dimension 5x1

array([[ 1.,  1.,  1.,  1.]])

## Transpose



$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m} \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
a_{11}  & a_{21} & \ldots & a_{n1} \\
a_{12}  & a_{22} & \ldots & a_{n2} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{1m}  & a_{2m} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{m\times n}$

$  \mathbf{A} = \begin{bmatrix}
\mathbf{c}_{1}  & \mathbf{c}_{1} & \ldots & \mathbf{c}_{m}
\end{bmatrix} \in \mathbb{R}^{n\times m}, 
\mathbf{c}_i = 
\begin{bmatrix}
a_{1i}  \\
a_{2i}  \\
\vdots \\
a_{ni}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{c}^T_{1}  \\
\mathbf{c}^T_{2}  \\
\vdots \\
\mathbf{c}^T_{m}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{c}^T_i = 
\begin{bmatrix}
a_{1i}  & a_{2i} & \ldots &a_{ni}  
\end{bmatrix} \in \mathbb{R}^{1\times n}
$

$  
\mathbf{A} = \begin{bmatrix}
\mathbf{r}_{1}  \\
\mathbf{r}_{2}  \\
\vdots \\
\mathbf{r}_{n}
\end{bmatrix}\in \mathbb{R}^{n\times m},
\mathbf{r}_i = 
\begin{bmatrix}
a_{i1}  & a_{i2} & \ldots &a_{im}  
\end{bmatrix} \in \mathbb{R}^{1\times m}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{r}^T_{1}  & \mathbf{r}^T_{1} & \ldots & \mathbf{r}^T_{n}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{r}^T_i = 
\begin{bmatrix}
a_{i1}  \\
a_{i2}  \\
\vdots \\
a_{im}  \\
\end{bmatrix} \in \mathbb{R}^{m\times 1}
$

In [201]:
A = np.random.randint(9,size=(5, 3)) # creates random matrix with integer entries (from 0-9) and size (5,3)
A

array([[5, 6, 4],
       [0, 0, 3],
       [2, 6, 0],
       [8, 1, 5],
       [1, 0, 2]])

In [202]:
A.shape

(5, 3)

In [203]:
A.T # returns matrix transpose

array([[5, 0, 2, 8, 1],
       [6, 0, 6, 1, 0],
       [4, 3, 0, 5, 2]])

In [204]:
A.T.shape

(3, 5)

In [205]:
b = np.random.randn(5,1) # column vector with normally distributed random entries
b

array([[-2.466],
       [-0.102],
       [-0.769],
       [-1.143],
       [ 0.165]])

In [206]:
b.T

array([[-2.466, -0.102, -0.769, -1.143,  0.165]])

Remember that $(\mathbf{A}^T)^T = \mathbf{A}$

In [207]:
b.T.T # b.T.T = b

array([[-2.466],
       [-0.102],
       [-0.769],
       [-1.143],
       [ 0.165]])

## Matrix addition

Matrix sum is only defined if matrices have the same dimension

$$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m},
 \mathbf{B} = \begin{bmatrix}
b_{11}  & b_{12} & \ldots & b_{1m} \\
b_{21}  & b_{22} & \ldots & b_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
b_{n1}  & b_{n2} &  \ldots & b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$

$$ \mathbf{A}+\mathbf{B} = \begin{bmatrix}
a_{11}+b_{11}  & a_{12}+b_{12} & \ldots & a_{1m}+b_{1m} \\
a_{21}+b_{21}  & a_{22}+b_{22} & \ldots & a_{2m}+b_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}+b_{n1}  & a_{n2}+b_{n2} &  \ldots & a_{nm}+b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$




In [208]:
A = np.random.randint(9,size=(3, 2)) # creates random matrix with integer entries (from 0-9) and size (5,3)
A

array([[1, 6],
       [5, 3],
       [5, 1]])

In [209]:
B = np.random.randint(9,size=(3, 2)) # creates random matrix with integer entries (from 0-9) and size (5,3)
B

array([[7, 1],
       [0, 3],
       [8, 6]])

In [210]:
A+B # matrix addition

array([[ 8,  7],
       [ 5,  6],
       [13,  7]])

In [211]:
C = np.random.randint(9,size=(3, 1)) # column vector dimension 3x1
C

array([[7],
       [8],
       [0]])

In [212]:
A+C

array([[ 8, 13],
       [13, 11],
       [ 5,  1]])

## Matrix multiplication

In [213]:
B.T @ B

array([[113,  55],
       [ 55,  46]])

In [214]:
A @ A.T

array([[37, 23, 11],
       [23, 34, 28],
       [11, 28, 26]])

In [215]:
Y = np.linalg.pinv(A)
print(Y)

[[-0.066  0.091  0.122]
 [ 0.168  0.014 -0.047]]


In [216]:
print(Y @ A)

[[  1.000e+00  -1.249e-16]
 [  1.110e-16   1.000e+00]]


In [217]:
X = A @ A.T
Xinv = np.linalg.inv(X)
print(X)
print(Xinv)
print(X @ Xinv)


[[37 23 11]
 [23 34 28]
 [11 28 26]]
[[  5.141e+14  -1.491e+15   1.388e+15]
 [ -1.491e+15   4.323e+15  -4.025e+15]
 [  1.388e+15  -4.025e+15   3.748e+15]]
[[  0.5  -8.    0.5]
 [ -6.    0.   10. ]
 [ -9.    0.    7. ]]


In [218]:
np.linalg.eig(X)

(array([  7.462e+01,   2.238e+01,   4.012e-15]),
 array([[-0.553, -0.797,  0.245],
        [-0.662,  0.241, -0.71 ],
        [-0.506,  0.554,  0.661]]))