# Introduction - Matrix algebra review

This page contains some basic reminder of matrix algebra using python numpy.

The following links has useful information whan converting from Matlab to numpy arrays:  
http://sebastianraschka.com/Articles/2014_matlab_vs_numpy.html  
https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#




Matrix with real elements:
$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$

The first index $n$ is the number of rows.  
The second index $m$ is the number of columns

Column vector of dimension $n$:
$\mathbf{a} = 
\begin{bmatrix}
a_{1}  \\
a_{2}  \\
\vdots \\
a_{n}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
$

Row vector of dimension $m$:

$\mathbf{b} = 
\begin{bmatrix}
b_1  & b_2 & \ldots b_{m} 
\end{bmatrix} \in \mathbb{R}^{1\times m}
$


In [116]:
import numpy as np
#from numpy import linalg as LA
np.set_printoptions(precision=3)

In [117]:
A = np.random.randint(9, size=(4, 5)) # creates random matrix with integer entries (from 0-9) and size (4,5)
A

array([[8, 1, 6, 7, 6],
       [0, 8, 6, 5, 6],
       [7, 4, 0, 3, 8],
       [7, 7, 5, 5, 7]])

In [118]:
a = np.array([[0],[2],[1],[6],[7]]) # numpy array representation of column vector as a 2d array of dimension (5,1)
a

array([[0],
       [2],
       [1],
       [6],
       [7]])

In [119]:
a.shape

(5, 1)

In [120]:
b = np.array([[1,2,3,6,7]]) # row vector
b

array([[1, 2, 3, 6, 7]])

In [121]:
b.shape

(1, 5)

In [122]:
np.zeros((5,1)) # column vector of zeros and dimension 5x1

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [123]:
np.ones((1,4)) # row vector of ones and dimension 5x1

array([[ 1.,  1.,  1.,  1.]])

## Transpose



$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m} \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
a_{11}  & a_{21} & \ldots & a_{n1} \\
a_{12}  & a_{22} & \ldots & a_{n2} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{1m}  & a_{2m} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{m\times n}$

$  \mathbf{A} = \begin{bmatrix}
\mathbf{c}_{1}  & \mathbf{c}_{1} & \ldots & \mathbf{c}_{m}
\end{bmatrix} \in \mathbb{R}^{n\times m}, 
\mathbf{c}_i = 
\begin{bmatrix}
c_{1i}  \\
c_{2i}  \\
\vdots \\
c_{ni}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{c}^T_{1}  \\
\mathbf{c}^T_{2}  \\
\vdots \\
\mathbf{c}^T_{m}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{c}^T_i = 
\begin{bmatrix}
c_{1i}  & c_{2i} & \ldots &c_{ni}  
\end{bmatrix} \in \mathbb{R}^{1\times n}
$

$  
\mathbf{A} = \begin{bmatrix}
\mathbf{r}_{1}  \\
\mathbf{r}_{2}  \\
\vdots \\
\mathbf{r}_{n}
\end{bmatrix}\in \mathbb{R}^{n\times m},
\mathbf{r}_i = 
\begin{bmatrix}
r_{i1}  & r_{i2} & \ldots &r_{im}  
\end{bmatrix} \in \mathbb{R}^{1\times m}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{r}^T_{1}  & \mathbf{r}^T_{1} & \ldots & \mathbf{r}^T_{m}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{r}^T_i = 
\begin{bmatrix}
r_{i1}  \\
r_{i2}  \\
\vdots \\
r_{im}  \\
\end{bmatrix} \in \mathbb{R}^{m\times 1}
$

In [124]:
A = np.random.randint(9,size=(5, 3)) # creates random matrix with integer entries (from 0-9) and size (5,3)
A

array([[7, 7, 6],
       [0, 0, 7],
       [6, 0, 6],
       [7, 4, 3],
       [8, 6, 7]])

In [125]:
A.transpose() # returns matrix transpose

array([[7, 0, 6, 7, 8],
       [7, 0, 0, 4, 6],
       [6, 7, 6, 3, 7]])

In [126]:
A.shape

(5, 3)

In [127]:
A.T # a shorter way of obtaining the same result transpose

array([[7, 0, 6, 7, 8],
       [7, 0, 0, 4, 6],
       [6, 7, 6, 3, 7]])

In [128]:
A.T.shape

(3, 5)

## Matrix sum

Matrix sum is only defined if matrices have the same dimension

$$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m},
 \mathbf{B} = \begin{bmatrix}
b_{11}  & b_{12} & \ldots & b_{1m} \\
b_{21}  & b_{22} & \ldots & b_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
b_{n1}  & b_{n2} &  \ldots & b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$

$$ \mathbf{A}+\mathbf{B} = \begin{bmatrix}
a_{11}+b_{11}  & a_{12}+b_{12} & \ldots & a_{1m}+b_{11} \\
a_{21}+b_{21}  & a_{22}+b_{22} & \ldots & a_{2m}+b_{1m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}+b_{n1}  & a_{n2}+b_{n2} &  \ldots & a_{nm}+b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$




## Matrix multiplication

In [129]:
B.T @ B

array([[123,  56],
       [ 56,  44]])

In [130]:
A @ A.T

array([[134,  42,  78,  95, 140],
       [ 42,  49,  42,  21,  49],
       [ 78,  42,  72,  60,  90],
       [ 95,  21,  60,  74, 101],
       [140,  49,  90, 101, 149]])

In [131]:
Y = np.linalg.pinv(A)
print(Y)

[[-0.049 -0.102  0.124  0.084  0.001]
 [ 0.118  0.01  -0.17  -0.023  0.044]
 [ 0.013  0.122  0.017 -0.044  0.014]]


In [132]:
print(Y @ A)

[[  1.000e+00   5.725e-17   1.223e-16]
 [ -3.886e-16   1.000e+00  -4.094e-16]
 [ -2.637e-16  -5.898e-17   1.000e+00]]


In [133]:
X = A @ A.T
Xinv = np.linalg.inv(X)
print(X)
print(Xinv)
print(X @ Xinv)


[[134  42  78  95 140]
 [ 42  49  42  21  49]
 [ 78  42  72  60  90]
 [ 95  21  60  74 101]
 [140  49  90 101 149]]
[[  1.196e+13   1.159e+14  -6.314e+13   2.440e+14  -1.766e+14]
 [ -5.674e+13  -1.572e+14   7.041e+13  -3.329e+14   2.881e+14]
 [  3.758e+13   1.352e+14  -6.475e+13   2.857e+14  -2.343e+14]
 [ -1.185e+14  -3.243e+14   1.447e+14  -6.869e+14   5.962e+14]
 [  6.508e+13   8.093e+13  -2.281e+13   1.732e+14  -1.914e+14]]
[[ 0.25  -1.125  0.844  7.5    1.5  ]
 [-0.312  1.406 -0.305  4.625 -0.875]
 [ 0.875 -2.438  0.828  8.25  -2.75 ]
 [ 0.438 -2.469 -0.648  7.125 -4.375]
 [ 0.438 -2.969  0.727  5.125 -2.375]]


In [134]:
np.linalg.eig(X)

(array([  4.208e+02,   4.339e+01,   1.377e+01,  -1.599e-14,   8.482e-15]),
 array([[-0.554, -0.226, -0.448,  0.561,  0.046],
        [-0.205,  0.824, -0.362, -0.307,  0.35 ],
        [-0.371,  0.383,  0.751,  0.389, -0.187],
        [-0.401, -0.341,  0.297, -0.616,  0.737],
        [-0.594, -0.083, -0.126, -0.244, -0.545]]))