# Introduction - Matrix algebra review

This page contains some basic reminder of matrix algebra using python numpy.

The following links has useful information whan converting from Matlab to numpy arrays:  
http://sebastianraschka.com/Articles/2014_matlab_vs_numpy.html  
https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#




Matrix with real elements:
$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$

The first index $n$ is the number of rows.  
The second index $m$ is the number of columns

Column vector of dimension $n$:
$\mathbf{a} = 
\begin{bmatrix}
a_{1}  \\
a_{2}  \\
\vdots \\
a_{n}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
$

Row vector of dimension $m$:

$\mathbf{b} = 
\begin{bmatrix}
b_1  & b_2 & \ldots b_{m} 
\end{bmatrix} \in \mathbb{R}^{1\times m}
$


In [1]:
import numpy as np
#from numpy import linalg as LA
np.set_printoptions(precision=2)

In [2]:
A = np.random.randint(9, size=(4, 5)) # creates random matrix with integer entries (from 0-9) and size (4,5)
A

array([[3, 0, 8, 1, 1],
       [3, 0, 1, 0, 4],
       [7, 7, 2, 2, 0],
       [3, 5, 7, 6, 3]])

In [3]:
a = np.array([[0],[2],[1],[6],[7]]) # numpy array representation of column vector as a 2d array of dimension (5,1)
a

array([[0],
       [2],
       [1],
       [6],
       [7]])

In [4]:
a.shape

(5, 1)

In [65]:
b = np.array([[1,2,3,6,7]]) # row vector of dimension (1,5)
b

array([[1, 2, 3, 6, 7]])

In [6]:
b.shape

(1, 5)

In [7]:
np.zeros((5,1)) # column vector of zeros and dimension 5x1

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [8]:
np.ones((1,4)) # row vector of ones and dimension 5x1

array([[ 1.,  1.,  1.,  1.]])

## Transpose



$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m} \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
a_{11}  & a_{21} & \ldots & a_{n1} \\
a_{12}  & a_{22} & \ldots & a_{n2} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{1m}  & a_{2m} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{m\times n}$

$  \mathbf{A} = \begin{bmatrix}
\mathbf{c}_{1}  & \mathbf{c}_{1} & \ldots & \mathbf{c}_{m}
\end{bmatrix} \in \mathbb{R}^{n\times m}, 
\mathbf{c}_i = 
\begin{bmatrix}
a_{1i}  \\
a_{2i}  \\
\vdots \\
a_{ni}  \\
\end{bmatrix} \in \mathbb{R}^{n\times 1}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{c}^T_{1}  \\
\mathbf{c}^T_{2}  \\
\vdots \\
\mathbf{c}^T_{m}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{c}^T_i = 
\begin{bmatrix}
a_{1i}  & a_{2i} & \ldots &a_{ni}  
\end{bmatrix} \in \mathbb{R}^{1\times n}
$

$  
\mathbf{A} = \begin{bmatrix}
\mathbf{r}_{1}  \\
\mathbf{r}_{2}  \\
\vdots \\
\mathbf{r}_{n}
\end{bmatrix}\in \mathbb{R}^{n\times m},
\mathbf{r}_i = 
\begin{bmatrix}
a_{i1}  & a_{i2} & \ldots &a_{im}  
\end{bmatrix} \in \mathbb{R}^{1\times m}
 \Longrightarrow
\mathbf{A}^T = \begin{bmatrix}
\mathbf{r}^T_{1}  & \mathbf{r}^T_{1} & \ldots & \mathbf{r}^T_{n}
\end{bmatrix} \in \mathbb{R}^{m\times n},
\mathbf{r}^T_i = 
\begin{bmatrix}
a_{i1}  \\
a_{i2}  \\
\vdots \\
a_{im}  \\
\end{bmatrix} \in \mathbb{R}^{m\times 1}
$

In [9]:
A = np.random.randint(9,size=(5, 3)) # creates random matrix with integer entries (from 0-9) and size (5,3)
A

array([[1, 5, 7],
       [6, 3, 3],
       [5, 3, 2],
       [7, 4, 7],
       [8, 3, 7]])

In [10]:
A.shape

(5, 3)

In [11]:
A.T # returns matrix transpose

array([[1, 6, 5, 7, 8],
       [5, 3, 3, 4, 3],
       [7, 3, 2, 7, 7]])

In [12]:
A.T.shape

(3, 5)

In [13]:
b = np.random.randn(5,1) # column vector with normally distributed random entries
b

array([[ 0.08],
       [-0.3 ],
       [-0.36],
       [ 1.67],
       [-1.23]])

In [14]:
b.T

array([[ 0.08, -0.3 , -0.36,  1.67, -1.23]])

Remember that $(\mathbf{A}^T)^T = \mathbf{A}$

In [15]:
b.T.T # b.T.T = b

array([[ 0.08],
       [-0.3 ],
       [-0.36],
       [ 1.67],
       [-1.23]])

## Matrix addition

Matrix sum is only defined if matrices have the same dimension

$$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m},
 \mathbf{B} = \begin{bmatrix}
b_{11}  & b_{12} & \ldots & b_{1m} \\
b_{21}  & b_{22} & \ldots & b_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
b_{n1}  & b_{n2} &  \ldots & b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$

$$ \mathbf{A}+\mathbf{B} = \begin{bmatrix}
a_{11}+b_{11}  & a_{12}+b_{12} & \ldots & a_{1m}+b_{1m} \\
a_{21}+b_{21}  & a_{22}+b_{22} & \ldots & a_{2m}+b_{2m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}+b_{n1}  & a_{n2}+b_{n2} &  \ldots & a_{nm}+b_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$$




In [16]:
A = np.random.randint(9,size=(3, 2)) # creates random matrix with integer entries (from 0-9) and size (5,3)
A

array([[7, 0],
       [2, 1],
       [1, 3]])

In [17]:
B = np.random.randint(9,size=(3, 2)) # creates random matrix with integer entries (from 0-9) and size (5,3)
B

array([[6, 1],
       [6, 2],
       [1, 0]])

In [18]:
A+B # matrix addition

array([[13,  1],
       [ 8,  3],
       [ 2,  3]])

Adding matrices of different dimension is strictly not defined. 
In numpy, it is possible to do so as far as one of the arrays has dimension 1.  
For details see http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [19]:
A

array([[7, 0],
       [2, 1],
       [1, 3]])

In [20]:
A+1 # here there is an addition of a 3x2 matrix plus a number. The number is added to all elements

array([[8, 1],
       [3, 2],
       [2, 4]])

In [21]:
C = np.array([[1],[2],[3]]) # column vector dimension 3x1
C

array([[1],
       [2],
       [3]])

In [22]:
A

array([[7, 0],
       [2, 1],
       [1, 3]])

In [23]:
A+C # in this case the vector C is copied to match the dimension of A. Is the same as A + [C C]

array([[8, 1],
       [4, 3],
       [4, 6]])

## Matrix multiplication

Matrix multiplication is only defined when the number of columns of the first matrix and the rows of the second are equal. 

$\mathbf{A} \in \mathbb{R}^{n\times m}, \mathbf{B} \in \mathbb{R}^{m\times p}
\Longrightarrow \mathbf{A}\mathbf{B}\in \mathbb{R}^{n\times p}
$

$(n\times m) \cdot (m\times p)\Longrightarrow (n\times p)$

$\mathbf{A} \in \mathbb{R}^{n\times m}, \mathbf{B} \in \mathbb{R}^{m\times p},
\mathbf{C} \in \mathbb{R}^{p\times q}
\Longrightarrow \mathbf{A}\mathbf{B}\mathbf{C}= (\mathbf{A}\mathbf{B})\mathbf{C} 
= \mathbf{A}(\mathbf{B}\mathbf{C})\in \mathbb{R}^{n\times q}
$

$(n\times m) \cdot (m\times p)\cdot (p\times q)\Longrightarrow (n\times q)$

One simple manner of visualizing matrix multiplication is to consider the rows of the first matrix against the columns of the second matrix. This is similar to a dot product interpretation of matrix multiplication and helps to gain insight and understanding.

$
\mathbf{A} = 
\begin{bmatrix}
\mathbf{a}_{1}  \\
\mathbf{a}_{2}  \\
\vdots \\
\mathbf{a}_{n}
\end{bmatrix}
\in \mathbb{R}^{n\times m},
\mathbf{a}_i = 
\begin{bmatrix}
a_{i1}  & a_{i2} & \ldots & a_{im}
\end{bmatrix}\in \mathbb{R}^{1\times m},
$

$\mathbf{B} = 
\begin{bmatrix}
\mathbf{b}_{1}  & \mathbf{b}_{2} & \ldots & \mathbf{b}_{p}
\end{bmatrix}\in \mathbb{R}^{m\times p},
\mathbf{b}_j = 
\begin{bmatrix}
b_{1j}  \\
b_{2j}  \\
\vdots \\
b_{mj}
\end{bmatrix}
\in \mathbb{R}^{m\times 1}
$


$\mathbf{A}\mathbf{B} = \begin{bmatrix}
\mathbf{a}_{1}  \\
\mathbf{a}_{2}  \\
\vdots \\
\mathbf{a}_{n}
\end{bmatrix}
\begin{bmatrix}
\mathbf{b}_{1}  & \mathbf{b}_{2} & \ldots & \mathbf{b}_{p}
\end{bmatrix}=
\begin{bmatrix}
\mathbf{a}_{1}\mathbf{b}_{1}  & \mathbf{a}_{1}\mathbf{b}_{2} & \ldots & \mathbf{a}_{1}\mathbf{b}_{p} \\
\mathbf{a}_{2}\mathbf{b}_{1}  & \mathbf{a}_{2}\mathbf{b}_{2} & \ldots & \mathbf{a}_{2}\mathbf{b}_{p} \\
\vdots  &  \vdots  & \ddots &  \vdots\\
\mathbf{a}_{n}\mathbf{b}_{1}  & \mathbf{a}_{n}\mathbf{b}_{2} & \ldots & \mathbf{a}_{n}\mathbf{b}_{p} \\
\end{bmatrix} \in \mathbb{R}^{n\times m}
$

where each of the entries is the cross product of a row of the first matrix and a column of the second: 

$\mathbf{a}_i \mathbf{b}_j = 
\begin{bmatrix}
a_{i1} & a_{i2} & \ldots & a_{im}
\end{bmatrix}
\begin{bmatrix}
b_{1j}  \\
b_{2j}  \\
\vdots  \\
b_{mj}
\end{bmatrix} = a_{i1}b_{1j}+a_{i2}b_{2j}+\ldots +a_{im}b_{mj} \in \mathbb{R}$


Matrix multiplication is done using the "@". Note that this is only valid for newer python versions.
In older versions matrix multiplication is obtained with the dot() command.

In [52]:
A = np.random.randint(5,size=(3, 2)) # creates random matrix with integer entries (from 0-5) and size (3,2)
A

array([[3, 1],
       [1, 3],
       [0, 2]])

In [53]:
B = np.random.randint(5,size=(2, 4))# creates random matrix with integer entries (from 0-5) and size (2,4)
B

array([[1, 2, 3, 2],
       [4, 3, 4, 2]])

In [54]:
A @ B

array([[ 7,  9, 13,  8],
       [13, 11, 15,  8],
       [ 8,  6,  8,  4]])

In [27]:
A @ A.T

array([[49, 14,  7],
       [14,  5,  5],
       [ 7,  5, 10]])

$\mathbf{A} \in \mathbb{R}^{n\times m}, \mathbf{B} \in \mathbb{R}^{m\times p}
\Longrightarrow (\mathbf{A}\mathbf{B})^T = \mathbf{B}^T\mathbf{A}^T\in \mathbb{R}^{p\times n}
$

$\mathbf{A} \in \mathbb{R}^{n\times m}, \mathbf{B} \in \mathbb{R}^{m\times p},
\mathbf{C} \in \mathbb{R}^{p\times q}
\Longrightarrow (\mathbf{A}\mathbf{B}\mathbf{C})^T= \mathbf{C}^T\mathbf{B}^T\mathbf{A}^T 
\in \mathbb{R}^{q\times n}
$

In [55]:
(A @ B).T

array([[ 7, 13,  8],
       [ 9, 11,  6],
       [13, 15,  8],
       [ 8,  8,  4]])

In [56]:
B.T @ A.T

array([[ 7, 13,  8],
       [ 9, 11,  6],
       [13, 15,  8],
       [ 8,  8,  4]])

In [57]:
C = np.random.randint(5,size=(4, 5))
C

array([[2, 2, 4, 2, 0],
       [4, 1, 0, 2, 0],
       [4, 2, 4, 4, 4],
       [1, 4, 3, 4, 1]])

In [58]:
(A @ B @ C).T

array([[110, 138,  76],
       [ 81,  99,  54],
       [104, 136,  76],
       [116, 140,  76],
       [ 60,  68,  36]])

In [59]:
C.T @ B.T @ A.T

array([[110, 138,  76],
       [ 81,  99,  54],
       [104, 136,  76],
       [116, 140,  76],
       [ 60,  68,  36]])

In [60]:
I = np.eye(4) # identity matrix of dimension 4
I

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [62]:
A = np.random.rand(4,4) # random matrix size (4x4)
A

array([[ 0.28,  0.29,  0.01,  0.63],
       [ 0.74,  0.02,  0.59,  0.18],
       [ 0.02,  0.66,  0.05,  0.04],
       [ 0.42,  0.46,  0.94,  0.77]])

In [63]:
A @ I

array([[ 0.28,  0.29,  0.01,  0.63],
       [ 0.74,  0.02,  0.59,  0.18],
       [ 0.02,  0.66,  0.05,  0.04],
       [ 0.42,  0.46,  0.94,  0.77]])

In [64]:
(A @ I) - A

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Matrix inversion

In [33]:
A = np.random.randn(4,4)
A

array([[ 0.44,  0.53,  0.23, -0.74],
       [-0.08, -0.07, -0.19, -0.43],
       [ 0.65,  0.11, -0.15,  1.47],
       [-1.  ,  0.98,  0.27, -0.28]])

In [34]:
np.linalg.inv(A)

array([[ 0.78,  0.03,  0.31, -0.46],
       [ 0.62,  1.09,  0.76,  0.68],
       [ 0.25, -4.38, -1.21, -0.32],
       [-0.37, -0.54,  0.36,  0.12]])

In [35]:
A @ np.linalg.inv(A) # the result is the identity matrix except for numerical accuracy in the order 10e-15

array([[  1.00e+00,  -5.55e-17,   0.00e+00,   0.00e+00],
       [ -2.78e-17,   1.00e+00,  -8.33e-17,  -2.08e-17],
       [  0.00e+00,   0.00e+00,   1.00e+00,   0.00e+00],
       [ -1.39e-17,   1.67e-16,   0.00e+00,   1.00e+00]])

In [36]:
Y = np.linalg.pinv(A)
print(Y)

[[ 0.78  0.03  0.31 -0.46]
 [ 0.62  1.09  0.76  0.68]
 [ 0.25 -4.38 -1.21 -0.32]
 [-0.37 -0.54  0.36  0.12]]


In [37]:
print(Y @ A)

[[  1.00e+00  -5.55e-17  -1.39e-17   2.22e-16]
 [  2.22e-16   1.00e+00   2.50e-16   3.33e-16]
 [ -1.11e-16   7.77e-16   1.00e+00   8.47e-16]
 [ -2.78e-17   1.39e-16  -1.53e-16   1.00e+00]]


In [38]:
X = A @ A.T
Xinv = np.linalg.inv(X)
print(X)
print(Xinv)
print(X @ Xinv)


[[ 1.07  0.2  -0.77  0.35]
 [ 0.2   0.23 -0.67  0.08]
 [-0.77 -0.67  2.63 -0.99]
 [ 0.35  0.08 -0.99  2.11]]
[[  1.19  -0.21   0.27  -0.06]
 [ -0.21  20.7    5.96   2.07]
 [  0.27   5.96   2.27   0.8 ]
 [ -0.06   2.07   0.8    0.78]]
[[  1.00e+00   8.88e-16  -2.78e-16   0.00e+00]
 [ -6.94e-18   1.00e+00   1.39e-17  -2.08e-17]
 [  3.47e-17   1.33e-15   1.00e+00   1.11e-16]
 [ -5.55e-17   0.00e+00  -2.22e-16   1.00e+00]]


In [39]:
np.linalg.eig(X)

(array([ 3.76,  1.48,  0.76,  0.04]), array([[ 0.3 ,  0.23, -0.93,  0.01],
        [ 0.17,  0.22,  0.11, -0.95],
        [-0.77, -0.44, -0.36, -0.28],
        [ 0.53, -0.84, -0.04, -0.1 ]]))