# Introduction - Matrix algebra review

$ \mathbf{A} = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{1m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$

$n$ is the number of rows

$m$ is the number of columns

$ A^T = \begin{bmatrix}
a_{11}  & a_{12} & \ldots & a_{1m} \\
a_{21}  & a_{22} & \ldots & a_{1m} \\        
\vdots  &  \vdots  & \ddots &  \vdots\\
a_{n1}  & a_{n2} &  \ldots & a_{nm}     
\end{bmatrix} \in \mathbb{R}^{n\times m}$

In [88]:
import numpy as np
#from numpy import linalg as LA
np.set_printoptions(precision=3)

In [89]:
A = np.random.randint(9, size=(4, 5))
print(A)

[[7 1 0 5 3]
 [7 2 1 0 0]
 [1 3 6 2 1]
 [7 8 1 1 5]]


In [90]:
B = np.random.randint(9, size=(4, 2))
print(B)

[[3 4]
 [3 2]
 [3 1]
 [6 4]]


In [91]:
print(B.T)

[[3 3 3 6]
 [4 2 1 4]]


In [92]:
B.T.dot(B) # B^T*B

array([[63, 45],
       [45, 37]])

In [93]:
B.T @ B

array([[63, 45],
       [45, 37]])

In [94]:
A @ A.T

array([[ 84,  51,  23,  77],
       [ 51,  54,  19,  66],
       [ 23,  19,  51,  44],
       [ 77,  66,  44, 140]])

In [95]:
Y = np.linalg.pinv(A)
print(Y)

[[ 0.024  0.144 -0.025 -0.023]
 [-0.07  -0.032  0.009  0.108]
 [-0.027  0.052  0.155 -0.051]
 [ 0.148 -0.112  0.045 -0.035]
 [ 0.055 -0.14  -0.02   0.078]]


In [96]:
print(Y @ A)

[[ 0.989  0.051 -0.028  0.047 -0.07 ]
 [ 0.051  0.756  0.132 -0.225  0.337]
 [-0.028  0.132  0.928  0.122 -0.183]
 [ 0.047 -0.225  0.122  0.793  0.311]
 [-0.07   0.337 -0.183  0.311  0.533]]


In [97]:
X = A @ A.T
Xinv = np.linalg.inv(X)
print(X)
print(Xinv)
print(X @ Xinv)


[[ 84  51  23  77]
 [ 51  54  19  66]
 [ 23  19  51  44]
 [ 77  66  44 140]]
[[  3.105e-02  -1.994e-02   6.750e-05  -7.699e-03]
 [ -1.994e-02   5.666e-02   2.013e-03  -1.638e-02]
 [  6.750e-05   2.013e-03   2.700e-02  -9.471e-03]
 [ -7.699e-03  -1.638e-02  -9.471e-03   2.207e-02]]
[[  1.000e+00   2.220e-16   0.000e+00   0.000e+00]
 [  1.110e-16   1.000e+00   1.110e-16  -2.220e-16]
 [  1.665e-16  -1.110e-16   1.000e+00   0.000e+00]
 [  2.220e-16   0.000e+00   2.220e-16   1.000e+00]]


In [98]:
np.linalg.eig(X)

(array([ 246.918,   41.758,   26.145,   14.178]),
 array([[ 0.503,  0.5  ,  0.585,  0.394],
        [ 0.404,  0.253,  0.028, -0.878],
        [ 0.26 , -0.804,  0.527, -0.095],
        [ 0.719, -0.202, -0.616,  0.253]]))